### ISSUE TITLE
Pools missing from network topology list

### ISSUE THREAD

**Issue by glitch40** [input-output-hk/cardano-ops#381]
The IO network topology file is missing several pools and relays for those pools reported at

https://explorer.mainnet.cardano.org/relays/topology.json 

One instance would be the relays for my pool 1LOVE which this pool has been up from the start of Main net and was previously listed in the topology, the registered DNS has remained the same is up and can be pinged at: relay.anonaf.com 3333 

There are multiple relays behind this DNS at all times.

**Comment by jbgi** [comment]
So it looks like one of your relay, `107.152.35.131`, is not responding to ping.
The current behavior is try to ping all relays behind the dns name. Thus this process timeout for your relay.
So short term solution would be to get back this relay up and running or removing it from dns.

Slightly longer term, we should probably improve the process so that only one relay ip be required to be up to include a relay dns name in the topology.

**Comment by glitch40** [comment]
Thanks for the reply, seems to be resolved by replacing that relay however would assume more pools suffer the same fate unknowingly if one of their relays is offline at the time of ping behind a dns.

**Comment by jbgi** [comment]
The script has been updated to include relays as soon as one of the IPs behind dns is responding to (cardano-)ping.
